# Generated by Django 5.1 on 2024-09-05 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('artiste', models.CharField(max_length=255)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('realisateur', models.CharField(max_length=255)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('auteur', models.CharField(max_length=255)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.AddField(
            model_name='media',
            name='emprunteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='mediatheque.emprunteur'),
        ),
    ]
