# Generated by Django 5.1 on 2024-09-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='disponible',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='mediatheque.emprunteur'),
        ),
    ]
