# Generated by Django 5.1 on 2024-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0002_alter_media_disponible_alter_media_emprunteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='realisateur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
