# Generated by Django 5.1 on 2024-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0003_alter_dvd_realisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='artiste',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
