# Generated by Django 5.1 on 2024-09-10 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0004_alter_cd_artiste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_retour', models.DateTimeField()),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.emprunteur')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.media')),
            ],
        ),
    ]
