# Generated by Django 5.1 on 2024-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0005_emprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunteur',
            name='nombre_emprunts',
            field=models.IntegerField(default=0),
        ),
    ]
